# Generated by Django 4.1.7 on 2024-05-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='ProfilResmi'),
        ),
    ]
